SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `#__notification_content` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`key` VARCHAR(200)  NOT NULL ,
`value` TEXT NOT NULL ,
`visibility` TINYINT(1)  NOT NULL ,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;