name: _offline
timestamp: 1519682534
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1509649909
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  logo:
    logo-5992: Logo
    logo-3639: 'Logo / Image'
  social:
    social-7220: Social
  simplecontent:
    simplecontent-5551: 'Photon is Coming Soon'
  content:
    system-content-5841: 'Page Content'
  blockcontent:
    blockcontent-4574: 'Maintenance Mode'
  newsletter:
    newsletter-9635: Newsletter
  copyright:
    copyright-5748: Copyright
inherit: {  }
