version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1509649909
layout:
  top: {  }
  navigation: {  }
  /slideshow/:
    -
      - owlcarousel-2627
    -
      - newsslider-1896
    -
      - custom-5713
  /header/:
    -
      - newsticker-4619
  /aboveBanner/: {  }
  /above/: {  }
  /showcaseBanner/: {  }
  /container-showcase/:
    -
      -
        'showcaseleft 68':
          -
            - contenttabs-6353
      -
        'showcaseright 32':
          -
            - custom-9187
          -
            - gridcontent-6371
          -
            0: 'gridstatistic-3794 50'
            block-5155: {  }
  /container-expanded/: {  }
  /utilityBanner/: {  }
  /utility/: {  }
  /featureBanner/:
    -
      - imagegrid-6202
  /feature/:
    -
      - testimonial-6115
  mainBanner: {  }
  /container-4448/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60': {  }
      -
        'aside 20':
          -
            - spacer-4358
  /expandedBanner/: {  }
  /expanded/: {  }
  /extensionBanner/: {  }
  /extension/: {  }
  /bottomBanner/:
    -
      - position-position-4953
  /bottom/:
    -
      - position-position-3343
  /footer/: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  slideshow:
    type: section
    attributes:
      boxed: '2'
      class: ''
  header:
    attributes:
      boxed: '1'
      class: box-top
  aboveBanner:
    type: section
    attributes:
      boxed: '1'
      class: ''
  above:
    type: section
    attributes:
      boxed: '1'
      class: ''
  showcaseBanner:
    type: section
    attributes:
      boxed: '1'
      class: ''
  showcaseleft:
    type: section
    attributes:
      class: ''
  block-5155:
    attributes:
      class: gm-success
  showcaseright:
    type: section
    attributes:
      class: ''
    block:
      class: 'nomarginall nopaddingall'
  container-showcase:
    attributes:
      boxed: '1'
      class: g-compact
      extra: {  }
  container-expanded:
    attributes:
      boxed: '1'
      class: nomarginbottom
      extra: {  }
  utilityBanner:
    type: section
    attributes:
      boxed: '0'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '1'
      class: ''
  featureBanner:
    type: section
    attributes:
      boxed: '1'
      class: ''
  feature:
    type: section
    attributes:
      boxed: '1'
      class: ''
  mainBanner:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  sidebar:
    type: section
    attributes:
      class: ''
    block:
      class: equal-height
  mainbar:
    type: section
    block:
      class: equal-height
  aside:
    block:
      class: equal-height
  container-4448:
    attributes:
      boxed: '1'
      class: ''
      extra: {  }
  expandedBanner:
    type: section
    attributes:
      boxed: '1'
      class: ''
  expanded:
    type: section
    attributes:
      boxed: '1'
      class: ''
  extensionBanner:
    type: section
    attributes:
      boxed: '1'
      class: ''
  extension:
    type: section
    attributes:
      boxed: '1'
      class: nomargintop
  bottomBanner:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: '0'
      class: ''
  footer:
    attributes:
      boxed: '0'
      class: ''
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2627:
    title: 'Owl Carousel'
    attributes:
      animateIn: ''
      loop: '1'
      autoplay: '1'
      items:
        -
          image: 'gantry-media://Banner_01.jpg'
          icon: ''
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttontarget: _self
          buttonclass: ''
          name: 'New item'
        -
          image: 'gantry-media://Banner_02.jpg'
          icon: ''
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttontarget: _self
          buttonclass: ''
          name: 'New item'
    block:
      class: g-bottom-offset
  newsslider-1896:
    title: 'News Slider'
    attributes:
      enabled: 0
      delay: '4000'
      class: g-bottom-offset
      title: ''
      items:
        -
          image: 'gantry-media://01a.jpg'
          desc: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          title: 'Gracias por ser parte de cada logro ¡Hoy también te celebramos, Feliz Navidad!'
        -
          image: 'gantry-media://Banner_02.jpg'
          desc: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          title: '¡Os pido Posada!'
        -
          image: 'gantry-media://Banner_03.jpg'
          desc: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          title: '¡Escoge tu regalo!'
        -
          image: 'gantry-media://Banner_04.jpg'
          desc: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          title: 'Que ésta Navidad convierta cada uno de tus deseos en realidad'
  custom-5713:
    title: 'Custom HTML'
    attributes:
      html: '<br><br>'
  newsticker-4619:
    title: 'News Ticker'
    attributes:
      enabled: 0
      speed: fast
      Interval: '5000'
      Direction: down
      class: ''
      label: Noticias
      items:
        -
          content: '¡Prepárate para escoger tu premio!'
          readmoretext: ''
          readmorelink: ''
          readmoretarget: _self
          title: Proximo
    block:
      variations: nopaddingall
  contenttabs-6353:
    title: 'Content Tabs'
    attributes:
      items:
        -
          tabname: Bienvenida
          title: 'Bienvenido a'
          subtitle: ''
          desc: "<div id=\"box-intro\">\n<img src=\"gantry-media://global/Incentiva-05.png\">\n\n<p>\n\t¡Es momento de agradecerte por ser parte de grandes logros juntos!\n<br><br>\n\n\tAquí podrás canjear tus certificados de <i>regalo / puntos</i> por los <b>premios<br> que más te gusten </b> dentro de las diferentes categorías que tenemos <br>disponibles para ti.\n</p>\n</div>\n"
          tags: {  }
          name: Bienvenida
    block:
      class: 'wow fadeInUp'
  custom-9187:
    title: 'Custom HTML'
    attributes:
      enabled: 0
      html: '<h1>Hola</h>'
    block:
      class: 'wow slideInUp'
  gridcontent-6371:
    title: 'Grid Content'
    attributes:
      enabled: 0
      gridcontentitems:
        -
          icon: 'fa fa-user'
          iconcolor: accent1
          desc: '75'
          link: ''
          title: Usuarios
    block:
      class: 'moduletable nomarginall nopaddingall wow slideInUp'
  gridstatistic-3794:
    title: 'Grid Statistic'
    attributes:
      title: 'Un programa exitoso.'
      gridstatisticitems:
        -
          icon: 'fa fa-user'
          text1: '72'
          text2: Usuarios
          title: Usuarios
    block:
      id: home_counter
      class: 'box-success wow slideInUp'
  imagegrid-6202:
    title: 'Image Grid'
    attributes:
      class: g-bottom-offset
      cols: g-imagegrid-3cols
      imagegriditems:
        -
          image: 'gantry-media://Articulos_Viaje.jpg'
          caption: 'Artículos de Viaje'
          url: 'catalogo.html?task=sortField&categories=2'
          title: 'Artículos de Viaje'
        -
          image: 'gantry-media://Aventura_Aire.jpg'
          caption: 'Aventuras al aire libre'
          url: 'catalogo.html?task=sortField&categories=9'
          title: 'Aventura al aire Libre'
        -
          image: 'gantry-media://Decoracion y Hogar.jpg'
          caption: 'Decoración y Hogar'
          url: 'catalogo.html?task=sortField&categories=4'
          title: 'Decoración y Hogar'
        -
          image: 'gantry-media://Entretenimiento.jpg'
          caption: Entretenimiento
          url: 'catalogo.html?task=sortField&categories=12'
          title: Entretenimiento
        -
          image: 'gantry-media://Experiencias.jpg'
          caption: Experiencias
          url: 'catalogo.html?task=sortField&categories=10'
          title: Experiencias
        -
          image: 'gantry-media://Viajes.jpg'
          caption: Viajes
          url: 'catalogo.html?task=sortField&categories=15'
          title: Viajes
        -
          image: 'gantry-media://Relojes_01.jpg'
          caption: Relojes
          url: 'catalogo.html?task=sortField&categories=11'
          title: Relojes
        -
          image: 'gantry-media://Linea_Blanca.jpg'
          caption: 'Línea Blanca'
          url: 'catalogo.html?task=sortField&categories=5'
          title: 'Línea Blanca'
        -
          image: 'gantry-media://Tecnologia.jpg'
          caption: Tecnología
          url: 'catalogo.html?task=sortField&categories=14'
          title: Tencnología
    block:
      class: 'wow fadeInUp'
  testimonial-6115:
    attributes:
      enabled: 0
      class: 'wow zoomIn'
      intro: Testimonios
      cols: g-3cols
      testimonials:
        -
          style: g-testimonial-standard
          img: 'gantry-media://home/testimoniales/people1.JPG'
          content: 'Suspendisse potenti. Nulla ullamcorper lacus vitae erat sagittis, eget pellentesque justo ornare. Integer in vulputate purus. Aliquam feugiat laoreet mauris, et lobortis augue pulvinar nec.'
          author: 'Pedro Ramirez'
          company: ''
          companyurl: ''
          title: Pedro
        -
          style: g-testimonial-standard
          img: 'gantry-media://home/testimoniales/people3.jpg'
          content: 'Integer a dictum massa. Quisque tincidunt magna in tempor varius. In eu ullamcorper neque, vitae feugiat felis. Pellentesque sed nunc a arcu accumsan convallis. In hac habitasse platea dictumst.'
          author: 'Karla Sánchez'
          company: ''
          companyurl: ''
          title: Karla
        -
          style: g-testimonial-standard
          img: 'gantry-media://home/testimoniales/people2.JPG'
          content: 'Integer a dictum massa. Quisque tincidunt magna in tempor varius. In eu ullamcorper neque, vitae feugiat felis. Pellentesque sed nunc a arcu accumsan convallis.'
          author: 'Susana Alfaro'
          company: ''
          companyurl: ''
          title: Susana
  position-position-4953:
    title: 'Bottom Banner A'
    attributes:
      key: bottom-banner-a
  position-position-3343:
    title: 'Bottom A'
    attributes:
      key: bottom-a
