atoms:
  -
    title: Hover
    type: hover
    attributes:
      enabled: true
    id: hover-4659
  -
    id: bg-video-7876
    type: bg-video
    title: BG-Video
    attributes:
      enabled: '1'
      jquery: '1'
      urlVideo: 'https://www.youtube.com/watch?v=VTH1zCgC1kI'
      controls: '0'
      loop: '1'
      opacity: '1'
      mute: '1'
      startAt: '1'
  -
    id: block-application-1683
    type: block-application
    title: 'Block Application'
    attributes:
      enabled: '1'
